const DestinyData
=[
    {   
        id:1,
        city:"India",
        img:require('../Images/INDIA.jpg')
    }
    ,
    {   
        id:2,
        city:"China",
        img:require('../Images/CHINA.jpg')
    }
    ,
    {
        id:3,
        city:"Indonesia",
        img:require('../Images/INDONESIA.webp')
    },
    {
        id:4,
        city:"Japan",
        img:require('../Images/JAPAN2.jpeg')
    },
    {
        id:5,
        city:"Nepal",
        img:require('../Images/NEPAL.webp')
    },
    {
        id:6,
        city:"Malaysia",
        img:require('../Images/Malaysia.webp')
    },
    {
        id:7,
        city:"Vietnam",
        img:require('../Images/VIETNAM.jpg')
    },
    {
        id:8,
        city:"Thailand",
        img:require('../Images/THAILAND.jpg')
    }
    ,
    {
        id:9,
        city:"Germany",
        img:require('../Images/GERMANY.jpeg')
    }
    ,
    {
        id:10,
        city:"Norway",
        img:require('../Images/NORWAY.webp')
    }
    ,
    {
        id:11,
        city:"Spain",
        img:require('../Images/SPAIN.jpg')
    }
    ,
    {
        id:12,
        city:"Switzerland",
        img:require('../Images/SWITZERLAND.webp')
    }
    ,
    {
        id:13,
        city:"Itlay",
        img:require('../Images/ITLAY.jpg')
    }
    ,
    {
        id:14,
        city:"Argentina",
        img:require('../Images/ARGENTINA.png')
    }
    ,
    {
        id:15,
        city:"Brazil",
        img:require('../Images/BRAZIL.png')
    }
    ,
    {
        id:16,
        city:"Chile",
        img:require('../Images/CHILE.png')
    }
    ,
    {
        id:17,
        city:"Colombia",
        img:require('../Images/COLOMBIA.png')
    }
    ,
    {
        id:18,
        city:"Guyana",
        img:require('../Images/GUYANA.png')
    }
,
    {
        id:19,
        city:"Paraguay",
        img:require('../Images/PARAGUAY.png')
    }
    ,
    {
        id:20,
        city:"South Africa",
        img:require('../Images/SOUTH AFRICA.webp')
    }
    ,
    {
        id:21,
        city:"Morocco",
        img:require('../Images/MOROCCO.jpg')
    }
    ,
    {
        id:22,
        city:"Egypt",
        img:require('../Images/EGYPY.jpg')
    }
    ,
    {
        id:24,
        city:"Guniea",
        img:require('../Images/GUNIEA.jpg')
    }
    ,
    {
        id:23,
        city:"Mali",
        img:require('../Images/MALI.jpg')
    }
    ,
    {
        id:25,
        city:"Nica",
        img:require('../Images/NICA.webp')
    }

    ]
export default DestinyData